<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\StockExchange;

class StockExchangesTableSeeder extends Seeder
{
    public function run(): void
    {
        $exchanges = [
            ['name' => 'US OTC', 'country' => 'United States', 'code' => 'OTC', 'currency' => 'USD', 'stocks' => 9933],
            ['name' => 'Bombay Stock Exchange', 'country' => 'India', 'code' => 'BOM', 'currency' => 'INR', 'stocks' => 4553],
            ['name' => 'Tokyo Stock Exchange', 'country' => 'Japan', 'code' => 'TYO', 'currency' => 'JPY', 'stocks' => 3873],
            ['name' => 'London Stock Exchange', 'country' => 'United Kingdom', 'code' => 'LON', 'currency' => 'GBP', 'stocks' => 3417],
            ['name' => 'Nasdaq Stock Market', 'country' => 'United States', 'code' => 'NASDAQ', 'currency' => 'USD', 'stocks' => 3350],
            ['name' => 'Shenzhen Stock Exchange', 'country' => 'China', 'code' => 'SHE', 'currency' => 'CNY', 'stocks' => 2900],
            ['name' => 'National Stock Exchange of India', 'country' => 'India', 'code' => 'NSE', 'currency' => 'INR', 'stocks' => 2732],
            ['name' => 'Hong Kong Stock Exchange', 'country' => 'Hong Kong', 'code' => 'HKG', 'currency' => 'HKD', 'stocks' => 2637],
            ['name' => 'Shanghai Stock Exchange', 'country' => 'China', 'code' => 'SHA', 'currency' => 'CNY', 'stocks' => 2313],
            ['name' => 'Frankfurt Stock Exchange', 'country' => 'Germany', 'code' => 'FRA', 'currency' => 'EUR', 'stocks' => 2242],
            ['name' => 'New York Stock Exchange', 'country' => 'United States', 'code' => 'NYSE', 'currency' => 'USD', 'stocks' => 1936],
            ['name' => 'Australian Securities Exchange', 'country' => 'Australia', 'code' => 'ASX', 'currency' => 'AUD', 'stocks' => 1771],
            ['name' => 'KOSDAQ', 'country' => 'South Korea', 'code' => 'KOSDAQ', 'currency' => 'KRW', 'stocks' => 1761],
            ['name' => 'TSX Venture Exchange', 'country' => 'Canada', 'code' => 'TSXV', 'currency' => 'CAD', 'stocks' => 1462],
            ['name' => 'Taipei Exchange', 'country' => 'Taiwan', 'code' => 'TPEX', 'currency' => 'TWD', 'stocks' => 1173],
            ['name' => 'Borsa Italiana', 'country' => 'Italy', 'code' => 'BIT', 'currency' => 'EUR', 'stocks' => 1159],
            ['name' => 'Taiwan Stock Exchange', 'country' => 'Taiwan', 'code' => 'TPE', 'currency' => 'TWD', 'stocks' => 1072],
            ['name' => 'Bursa Malaysia', 'country' => 'Malaysia', 'code' => 'KLSE', 'currency' => 'MYR', 'stocks' => 1053],
            ['name' => 'Stock Exchange of Thailand', 'country' => 'Thailand', 'code' => 'BKK', 'currency' => 'THB', 'stocks' => 1042],
            ['name' => 'Korea Stock Exchange', 'country' => 'South Korea', 'code' => 'KRX', 'currency' => 'KRW', 'stocks' => 907],
            ['name' => 'Indonesia Stock Exchange', 'country' => 'Indonesia', 'code' => 'IDX', 'currency' => 'IDR', 'stocks' => 902],
            ['name' => 'Deutsche Börse Xetra', 'country' => 'Germany', 'code' => 'ETR', 'currency' => 'EUR', 'stocks' => 882],
            ['name' => 'Nasdaq Stockholm', 'country' => 'Sweden', 'code' => 'STO', 'currency' => 'SEK', 'stocks' => 770],
            ['name' => 'Euronext Paris', 'country' => 'France', 'code' => 'EPA', 'currency' => 'EUR', 'stocks' => 738],
            ['name' => 'Warsaw Stock Exchange', 'country' => 'Poland', 'code' => 'WSE', 'currency' => 'PLN', 'stocks' => 716],
            ['name' => 'Toronto Stock Exchange', 'country' => 'Canada', 'code' => 'TSX', 'currency' => 'CAD', 'stocks' => 704],
            ['name' => 'Canadian Securities Exchange', 'country' => 'Canada', 'code' => 'CSE', 'currency' => 'CAD', 'stocks' => 656],
            ['name' => 'Mexican Stock Exchange', 'country' => 'Mexico', 'code' => 'BMV', 'currency' => 'MXN', 'stocks' => 651],
            ['name' => 'London Stock Exchange AIM', 'country' => 'United Kingdom', 'code' => 'AIM', 'currency' => 'GBP', 'stocks' => 622],
            ['name' => 'Istanbul Stock Exchange', 'country' => 'Turkey', 'code' => 'IST', 'currency' => 'TRY', 'stocks' => 586],
            ['name' => 'Tel Aviv Stock Exchange', 'country' => 'Israel', 'code' => 'TLV', 'currency' => 'ILS', 'stocks' => 500],
            ['name' => 'Vienna Stock Exchange', 'country' => 'Austria', 'code' => 'VIE', 'currency' => 'EUR', 'stocks' => 483],
            ['name' => 'Pakistan Stock Exchange', 'country' => 'Pakistan', 'code' => 'PSX', 'currency' => 'PKR', 'stocks' => 480],
            ['name' => 'Brazil Stock Exchange', 'country' => 'Brazil', 'code' => 'BVMF', 'currency' => 'BRL', 'stocks' => 425],
            ['name' => 'Singapore Exchange', 'country' => 'Singapore', 'code' => 'SGX', 'currency' => 'SGD', 'stocks' => 397],
            ['name' => 'Ho Chi Minh Stock Exchange', 'country' => 'Vietnam', 'code' => 'HOSE', 'currency' => 'VND', 'stocks' => 390],
            ['name' => 'Saudi Stock Exchange', 'country' => 'Saudi Arabia', 'code' => 'TADAWUL', 'currency' => 'SAR', 'stocks' => 373],
            ['name' => 'Dhaka Stock Exchange', 'country' => 'Bangladesh', 'code' => 'DSE', 'currency' => 'BDT', 'stocks' => 356],
            ['name' => 'Oslo Børs', 'country' => 'Norway', 'code' => 'OSL', 'currency' => 'NOK', 'stocks' => 296],
            ['name' => 'Colombo Stock Exchange', 'country' => 'Sri Lanka', 'code' => 'COSE', 'currency' => 'LKR', 'stocks' => 294],
            ['name' => 'Hanoi Stock Exchange', 'country' => 'Vietnam', 'code' => 'HNX', 'currency' => 'VND', 'stocks' => 288],
            ['name' => 'Philippine Stock Exchange', 'country' => 'Philippines', 'code' => 'PSE', 'currency' => 'PHP', 'stocks' => 284],
            ['name' => 'Johannesburg Stock Exchange', 'country' => 'South Africa', 'code' => 'JSE', 'currency' => 'ZAR', 'stocks' => 270],
            ['name' => 'SIX Swiss Exchange', 'country' => 'Switzerland', 'code' => 'SWX', 'currency' => 'CHF', 'stocks' => 266],
            ['name' => 'Madrid Stock Exchange', 'country' => 'Spain', 'code' => 'BME', 'currency' => 'EUR', 'stocks' => 243],
            ['name' => 'NYSE American', 'country' => 'United States', 'code' => 'AMEX', 'currency' => 'USD', 'stocks' => 227],
            ['name' => 'Egyptian Stock Exchange', 'country' => 'Egypt', 'code' => 'EGX', 'currency' => 'EGP', 'stocks' => 220],
            ['name' => 'Santiago Stock Exchange', 'country' => 'Chile', 'code' => 'SNSE', 'currency' => 'CLP', 'stocks' => 194],
            ['name' => 'Nasdaq Helsinki', 'country' => 'Finland', 'code' => 'HEL', 'currency' => 'EUR', 'stocks' => 188],
            ['name' => 'Bucharest Stock Exchange', 'country' => 'Romania', 'code' => 'BVB', 'currency' => 'RON', 'stocks' => 185],
            ['name' => 'Moscow Stock Exchange', 'country' => 'Russia', 'code' => 'MOEX', 'currency' => 'RUB', 'stocks' => 185],
            ['name' => 'Buenos Aires Stock Exchange', 'country' => 'Argentina', 'code' => 'BCBA', 'currency' => 'ARS', 'stocks' => 176],
            ['name' => 'Lima Stock Exchange', 'country' => 'Peru', 'code' => 'BVL', 'currency' => 'PEN', 'stocks' => 170],
            ['name' => 'Singapore Exchange - Catalist', 'country' => 'Singapore', 'code' => 'SGXC', 'currency' => 'SGD', 'stocks' => 169],
            ['name' => 'Copenhagen Stock Exchange', 'country' => 'Denmark', 'code' => 'CPH', 'currency' => 'DKK', 'stocks' => 155],
            ['name' => 'Athens Stock Exchange', 'country' => 'Greece', 'code' => 'ATH', 'currency' => 'EUR', 'stocks' => 145],
            ['name' => 'Nigerian Stock Exchange', 'country' => 'Nigeria', 'code' => 'NGX', 'currency' => 'NGN', 'stocks' => 144],
            ['name' => 'Kuwait Stock Exchange', 'country' => 'Kuwait', 'code' => 'KWSE', 'currency' => 'KWD', 'stocks' => 140],
            ['name' => 'Cboe Canada', 'country' => 'Canada', 'code' => 'NEO', 'currency' => 'CAD', 'stocks' => 126],
            ['name' => 'Euronext Brussels', 'country' => 'Belgium', 'code' => 'EBR', 'currency' => 'EUR', 'stocks' => 125],
            ['name' => 'Amman Stock Exchange', 'country' => 'Jordan', 'code' => 'ASE', 'currency' => 'JOD', 'stocks' => 118],
            ['name' => 'Euronext Amsterdam', 'country' => 'Netherlands', 'code' => 'AMS', 'currency' => 'EUR', 'stocks' => 116],
            ['name' => 'New Zealand Stock Exchange', 'country' => 'New Zealand', 'code' => 'NZE', 'currency' => 'NZD', 'stocks' => 115],
            ['name' => 'Korea New Exchange', 'country' => 'South Korea', 'code' => 'XKON', 'currency' => 'KRW', 'stocks' => 114],
            ['name' => 'Stuttgart Stock Exchange', 'country' => 'Germany', 'code' => 'BST', 'currency' => 'EUR', 'stocks' => 108],
            ['name' => 'Nordic Growth Market', 'country' => 'Sweden', 'code' => 'NGM', 'currency' => 'SEK', 'stocks' => 108],
            ['name' => 'Muscat Securities Market', 'country' => 'Oman', 'code' => 'MSM', 'currency' => 'OMR', 'stocks' => 103],
            ['name' => 'Abu Dhabi Securities Exchange', 'country' => 'United Arab Emirates', 'code' => 'ADX', 'currency' => 'AED', 'stocks' => 102],
            ['name' => 'Luxembourg Stock Exchange', 'country' => 'Luxembourg', 'code' => 'LUX', 'currency' => 'EUR', 'stocks' => 101],
            ['name' => 'Jamaica Stock Exchange', 'country' => 'Jamaica', 'code' => 'JMSE', 'currency' => 'JMD', 'stocks' => 99],
            ['name' => 'Mauritius Stock Exchange', 'country' => 'Mauritius', 'code' => 'MUSE', 'currency' => 'MUR', 'stocks' => 86],
            ['name' => 'Hamburg Stock Exchange', 'country' => 'Germany', 'code' => 'HAM', 'currency' => 'EUR', 'stocks' => 78],
            ['name' => 'Bulgarian Stock Exchange', 'country' => 'Bulgaria', 'code' => 'BUL', 'currency' => 'BGN', 'stocks' => 76],
            ['name' => 'Casablanca Stock Exchange', 'country' => 'Morocco', 'code' => 'CBSE', 'currency' => 'MAD', 'stocks' => 75],
            ['name' => 'Colombia Stock Exchange', 'country' => 'Colombia', 'code' => 'BVC', 'currency' => 'COP', 'stocks' => 74],
            ['name' => 'Tunis Stock Exchange', 'country' => 'Tunisia', 'code' => 'BVMT', 'currency' => 'TND', 'stocks' => 72],
            ['name' => 'Aquis Exchange', 'country' => 'United Kingdom', 'code' => 'AQU', 'currency' => 'GBP', 'stocks' => 68],
            ['name' => 'Munich Stock Exchange', 'country' => 'Germany', 'code' => 'MUN', 'currency' => 'EUR', 'stocks' => 63],
            ['name' => 'Dubai Financial Market', 'country' => 'United Arab Emirates', 'code' => 'DFM', 'currency' => 'AED', 'stocks' => 59],
            ['name' => 'Nairobi Stock Exchange', 'country' => 'Kenya', 'code' => 'NASE', 'currency' => 'KES', 'stocks' => 57],
            ['name' => 'Budapest Stock Exchange', 'country' => 'Hungary', 'code' => 'BUD', 'currency' => 'HUF', 'stocks' => 55],
            ['name' => 'Nagoya Stock Exchange', 'country' => 'Japan', 'code' => 'XNGO', 'currency' => 'JPY', 'stocks' => 55],
            ['name' => 'Qatar Stock Exchange', 'country' => 'Qatar', 'code' => 'QSE', 'currency' => 'QAR', 'stocks' => 54],
            ['name' => 'Zagreb Stock Exchange', 'country' => 'Croatia', 'code' => 'ZSE', 'currency' => 'EUR', 'stocks' => 53],
            ['name' => 'Prague Stock Exchange', 'country' => 'Czech Republic', 'code' => 'PRA', 'currency' => 'CZK', 'stocks' => 53],
            ['name' => 'Euronext Lisbon', 'country' => 'Portugal', 'code' => 'ELI', 'currency' => 'EUR', 'stocks' => 46],
            ['name' => 'Ivory Coast Stock Exchange', 'country' => 'Ivory Coast', 'code' => 'BRVM', 'currency' => 'XOF', 'stocks' => 46],
            ['name' => 'Dusseldorf Stock Exchange', 'country' => 'Germany', 'code' => 'DUSE', 'currency' => 'EUR', 'stocks' => 40],
            ['name' => 'Cyprus Stock Exchange', 'country' => 'Cyprus', 'code' => 'CYS', 'currency' => 'EUR', 'stocks' => 39],
            ['name' => 'Spotlight Stock Market', 'country' => 'Sweden', 'code' => 'XSAT', 'currency' => 'SEK', 'stocks' => 37],
            ['name' => 'Nasdaq Iceland', 'country' => 'Iceland', 'code' => 'ICE', 'currency' => 'ISK', 'stocks' => 32],
            ['name' => 'Palestine Stock Exchange', 'country' => 'Palestine', 'code' => 'PEX', 'currency' => 'JOD', 'stocks' => 32],
            ['name' => 'Namibian Stock Exchange', 'country' => 'Namibia', 'code' => 'NMSE', 'currency' => 'NAD', 'stocks' => 31],
            ['name' => 'Malta Stock Exchange', 'country' => 'Malta', 'code' => 'MSE', 'currency' => 'EUR', 'stocks' => 29],
            ['name' => 'Bahrain Stock Exchange', 'country' => 'Bahrain', 'code' => 'BAX', 'currency' => 'BHD', 'stocks' => 29],
            ['name' => 'Nasdaq Tallinn', 'country' => 'Estonia', 'code' => 'TAL', 'currency' => 'EUR', 'stocks' => 28],
            ['name' => 'Tanzania Stock Exchange', 'country' => 'Tanzania', 'code' => 'DAR', 'currency' => 'TZS', 'stocks' => 28],
            ['name' => 'Nasdaq Vilnius', 'country' => 'Lithuania', 'code' => 'VSE', 'currency' => 'EUR', 'stocks' => 27],
            ['name' => 'Nasdaq Riga', 'country' => 'Latvia', 'code' => 'RSE', 'currency' => 'EUR', 'stocks' => 26],
            ['name' => 'Bermuda Stock Exchange', 'country' => 'Bermuda', 'code' => 'BSX', 'currency' => 'BMD', 'stocks' => 25],
            ['name' => 'Almaty Stock Exchange', 'country' => 'Kazakhstan', 'code' => 'KASE', 'currency' => 'KZT', 'stocks' => 21],
            ['name' => 'Beirut Stock Exchange', 'country' => 'Lebanon', 'code' => 'BSE', 'currency' => 'LBP', 'stocks' => 21],
            ['name' => 'Lusaka Stock Exchange', 'country' => 'Zambia', 'code' => 'LUSE', 'currency' => 'ZMW', 'stocks' => 21],
            ['name' => 'Rwanda Stock Exchange', 'country' => 'Rwanda', 'code' => 'RSE', 'currency' => 'RWF', 'stocks' => 13],
            ['name' => 'Ghana Stock Exchange', 'country' => 'Ghana', 'code' => 'GSE', 'currency' => 'GHS', 'stocks' => 12],
            ['name' => 'Botswana Stock Exchange', 'country' => 'Botswana', 'code' => 'BSEBW', 'currency' => 'BWP', 'stocks' => 12],
            ['name' => 'Uganda Securities Exchange', 'country' => 'Uganda', 'code' => 'USE', 'currency' => 'UGX', 'stocks' => 9],
            ['name' => 'Eswatini Stock Exchange', 'country' => 'Eswatini', 'code' => 'SSX', 'currency' => 'SZL', 'stocks' => 6],
            ['name' => 'Malawi Stock Exchange', 'country' => 'Malawi', 'code' => 'MSEMW', 'currency' => 'MWK', 'stocks' => 4],
        ];

        foreach ($exchanges as $exchange) {
            StockExchange::updateOrCreate(
                ['code' => $exchange['code']],
                $exchange
            );
        }
    }
}
